# Generated by Django 2.1.5 on 2019-01-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_fbv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
